name: study_buddy
description: A new Flutter project.
publish_to: "none"
version: 1.0.7+9

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.4.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.1.3
  cloud_functions: ^5.0.5
  firebase_app_check: ^0.3.0+1

  # Localization
  flutter_localizations:
    sdk: flutter
  flutter_gen: any

  # State & utils
  provider: ^6.1.2
  intl: ^0.20.2
  wakelock_plus: ^1.2.5

  # Google Sign-in + Drive
  google_sign_in: ^6.2.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  http: ^1.2.2
  url_launcher: ^6.3.0

  # Files / permissions
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  image_picker: ^1.1.1

  # Audio recorder
  record: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

dependency_overrides:
  record_linux: ^1.2.1
  record_platform_interface: ^1.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/app_icon.png

# flutter_launcher_icons configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon.png"

#flutter_intl:
#  enabled: true
#  arb_dir: lib/l10n
#  template_arbs:
#    - app_en.arb
#  output_dir: lib/l10n